# Node.js with gulp
# Build a Node.js project using the gulp task runner.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '21.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
- task: gulp@0
  inputs:
    gulpFile: 'gulpfile.mjs'
    targets: 
    gulpjs: 'node_modules/gulp/bin/gulp.js'
    enableCodeCoverage: false
    
- task: CmdLine@2
  inputs:
    script: 
      npm i -g tfx-cli
      cd dist/dev
      tfx extension create --manifest-globs vss-extension.json 
      cd ../qa
      tfx extension create --manifest-globs vss-extension.json
      cd ../prod && tfx extension create --manifest-globs vss-extension.json